### ISSUE TITLE
QT question

### ISSUE THREAD

**Issue by Guo-Shuai** [cuamckuu/SudokuSolver#1]
hello, I am a newer to QT. I tried to read your code and run it. It works well. But it confused me that there is no connect between button clicked signal and on_pushButton_clicked slot. How did it word?

**Comment by cuamckuu** [comment]
Hi. That's an old code, so I don't really know. I think that it is because of auto connections inside file"ui_sudokusolver.h". Also you can look to slots and signals from Qt Designer, try that, I guess, they should be there.

Some info about auto-connection:
http://doc.qt.io/qt-5/designer-using-a-ui-file.html#automatic-connections

**Comment by Guo-Shuai** [comment]
OK  thanks
